VB-3: Feature/connect open api tool
BinaryStudioAcademy/bsa-2022-vse-bude pull request #108
Opened 2022-08-19 17:24 UTC by mishabenq

![image](https://user-images.githubusercontent.com/92884408/185674099-235b82b6-3c7c-4eaf-805e-66e8e74b9031.png)

2022-08-20 06:09 UTC, Nightlngale requested changes
Routes !== Repository methods

2022-08-23 07:32 UTC, d-uvin commented on packages/backend/src/repositories/types/CreateRefreshToken.ts
> +type CreateRefreshToken = {
we kebab-case in files namings

2022-08-23 07:33 UTC, dmitriy-uvin commented on packages/backend/src/repositories/types/CreateRefreshToken.ts
> +type CreateRefreshToken = {
we use kebab-case in files namings

2022-08-23 07:33 UTC, dmitriy-uvin commented on packages/backend/src/repositories/types/CreateUser.ts
> +type CreateUser = {
also file name must use kebab-case

2022-08-23 07:34 UTC, dmitriy-uvin commented on packages/backend/src/server.ts
> +// import swaggerJsdoc from 'swagger-jsdoc';
remove comments

2022-08-23 07:34 UTC, dmitriy-uvin commented on packages/backend/src/server.ts
> +// const swaggerSpecification = swaggerJsdoc(options);
comments

2022-08-23 14:29 UTC, mishabenq commented
![image](https://user-images.githubusercontent.com/92884408/186184817-40800e3a-8fc3-4ea4-8ddd-47f10c0b1027.png)

2022-08-24 08:06 UTC, Vitalii4as requested changes

2022-08-24 08:06 UTC, Vitalii4as commented on packages/backend/tsconfig.json
> +    "experimentalDecorators": true,
We don't need it anymore

2022-08-24 08:06 UTC, Vitalii4as commented on packages/backend/package.json
> +    "tsoa": "^4.1.1",
Remove tsoa, dist and and tsoa.json

2022-08-24 10:19 UTC, Vitalii4as approved these changes

2022-08-24 10:19 UTC, merged