Feature/personal info
BinaryStudioAcademy/bsa-2022-vse-bude pull request #133
Opened 2022-08-24 18:49 UTC by YevheniiBieliaiev

In this version:
1. Fixed routes - now we have for account page - /account, for subpages (personal info) - /personal-info
Example of full route - /account/personal-info
2. Fixed mq styles of components, added new styles
3. Fixed localization according to new rules
4. Fixed styles of icons according to last changes
5. Added validation for Personal Info section of form
6. Added validation for Password Section of form
7. Added action for reset button - change user data to storage data
8. Deleted all actions and code for default avatar , setted only field for it and upload button
![only_current](https://user-images.githubusercontent.com/84641178/186499053-bd6d09a8-0f09-4440-a22a-d283f87e127d.png)
![same_emptyrepeat](https://user-images.githubusercontent.com/84641178/186499070-01624d8f-41f1-4003-983f-e5fca71bd130.png)
![notsame](https://user-images.githubusercontent.com/84641178/186499085-6c9fe58a-1ae1-41f0-8f5e-cd1d559f38f3.png)
![space](https://user-images.githubusercontent.com/84641178/186499096-63d70a63-5ea2-49cb-87ca-3c927fdc0a38.png)
![cyr](https://user-images.githubusercontent.com/84641178/186499105-1759f217-5456-491c-869a-4aeceb0a16c6.png)

2022-08-25 13:20 UTC, Nightlngale requested changes

2022-08-25 13:20 UTC, Nightlngale commented on packages/frontend/components/footer/links/policy.tsx
> +          color="YELLOW"
Let's use enum here

2022-08-25 13:20 UTC, Nightlngale commented on packages/frontend/components/primitives/dashboard-link/styles.ts
> +  height: 18px;
dashboard-link component is not a primitive(not used across the App) + use button for it

2022-08-25 13:20 UTC, Nightlngale commented on packages/frontend/components/primitives/download-button/component.tsx
> +        accept=".jpg, .png, .jpeg"
Let's have separate component

2022-08-25 13:20 UTC, Nightlngale commented on packages/frontend/components/sub-pages/user-account/personal-info/styles.ts
> +  margin-bottom: 20px;
theme

2022-08-25 13:54 UTC, YevheniiBieliaiev commented on packages/frontend/components/sub-pages/user-account/personal-info/styles.ts
> +  margin-bottom: 20px;
yup..))

2022-08-27 10:54 UTC, Nightlngale approved these changes

2022-08-29 08:57 UTC, merged