VB-290: fix lot section - small description text
BinaryStudioAcademy/bsa-2022-vse-bude pull request #309
Opened 2022-09-06 17:16 UTC by Dmytro-Dmytro

2022-09-06 17:49 UTC, voonya commented on packages/frontend/components/product/card/styles.ts
> +  min-height: 2.01rem;
use sizes from theme

2022-09-06 20:03 UTC, Nightlngale requested changes

2022-09-06 20:03 UTC, Nightlngale commented on packages/frontend/components/product/card/styles.ts
> +  min-height: ${2*/\d+/.exec(lineHeights.body2)}px;
I believe `${2*lineHeights.body2}px;` will work

2022-09-06 20:03 UTC, Nightlngale commented on packages/frontend/components/product/card/component.tsx
> +		  <StringCutter>{props.name}</StringCutter>
Formating

2022-09-06 20:26 UTC, Nightlngale approved these changes

2022-09-06 20:26 UTC, Nightlngale commented on packages/frontend/components/product/card/component.tsx
> +		</div>
Formating

2022-09-07 20:22 UTC, voonya approved these changes

2022-09-07 20:24 UTC, merged