VB-309: add functionality for checking ended auctions and sending not…
BinaryStudioAcademy/bsa-2022-vse-bude pull request #331
Opened 2022-09-07 20:53 UTC by dmitriy-uvin

…ifications to it's participants

2022-09-08 06:12 UTC, YevheniiBieliaiev approved these changes

2022-09-08 09:37 UTC, Vitalii4as requested changes
Use https://www.npmjs.com/package/node-schedule

2022-09-08 09:37 UTC, Vitalii4as commented on packages/backend/package.json
> +    "auction-notifications:prod": "node ./build/src/commands/index.ts auction-notifications"
It will not work

2022-09-08 09:37 UTC, Vitalii4as commented on packages/backend/package.json
> +    "ts-node": "^10.9.1",
It must be in devDependencies

2022-09-08 09:37 UTC, Vitalii4as commented
Or this https://www.npmjs.com/package/cron

2022-09-08 09:41 UTC, d-uvin commented on packages/backend/package.json
> +    "auction-notifications:prod": "node ./build/src/commands/index.ts auction-notifications"
why?

2022-09-08 17:54 UTC, Nightlngale requested changes

2022-09-08 17:54 UTC, Nightlngale commented on packages/backend/src/scheduler/index.ts
> +export const initAuctionJobs = (productRepository: ProductRepository) => {
How would you set a job for created in runtime auction. I believe,  it make sense to have a service with Api to add a job.

2022-09-09 06:07 UTC, Nightlngale requested changes

2022-09-09 06:07 UTC, Nightlngale commented on packages/backend/package.json
> +    "@types/node-schedule": "^2.1.0",
dev deps

2022-09-09 06:07 UTC, Nightlngale commented on packages/backend/src/services/product.ts
> +import { createAuctionJob, updateAuctionJob } from '@scheduler';
inject it via constructor

2022-09-09 08:36 UTC, Vitalii4as approved these changes

2022-09-09 10:28 UTC, merged