VB-321: Fix/personal info headers styles
BinaryStudioAcademy/bsa-2022-vse-bude pull request #345
Opened 2022-09-08 18:55 UTC by mishabenq

2022-09-08 18:55 UTC, mishabenq commented
![image](https://user-images.githubusercontent.com/92884408/189203258-e2d3184a-66be-4491-9ed8-33cc844a0398.png)

2022-09-08 19:24 UTC, Nightlngale requested changes

2022-09-08 19:24 UTC, Nightlngale commented on packages/frontend/components/profile/user-account/personal-info/styles.ts
>  export const groupePhone = ({ spaces }: Theme) => css`
typo

2022-09-08 20:51 UTC, voonya approved these changes

2022-09-08 23:59 UTC, double-hope approved these changes

2022-09-09 07:48 UTC, mishabenq commented on packages/frontend/components/profile/user-account/personal-info/styles.ts
>  export const groupePhone = ({ spaces }: Theme) => css`
fixed

2022-09-09 07:59 UTC, merged