Feature/my list card
BinaryStudioAcademy/bsa-2022-vse-bude pull request #349
Opened 2022-09-09 07:39 UTC by YevheniiBieliaiev

Added card components
Added store
Changed fetching of items data on back

2022-09-09 13:47 UTC, Nightlngale requested changes

2022-09-09 13:47 UTC, Nightlngale commented on packages/backend/src/api/routes/profile.ts
> +      console.log(posted);
log

2022-09-09 13:47 UTC, Nightlngale commented on packages/backend/src/api/routes/profile.ts
> +      const posted = await myListService.getPostedItems({ userId });
promise.all

2022-09-09 13:47 UTC, Nightlngale commented on packages/frontend/components/profile/user-account/my-list/primitives/styles.ts
> +    width: 102px;
why 102

2022-09-09 13:47 UTC, Nightlngale commented on packages/frontend/components/profile/user-account/my-list/tmp-element-charity/styles.ts
> +export const nameWrapper = () => css``;
remove empty stuff

2022-09-11 13:37 UTC, Nightlngale requested changes

2022-09-11 13:37 UTC, Nightlngale commented on packages/frontend/components/profile/user-account/my-list/cards/types.ts
> +}
We can have a base interface with common props

2022-09-11 13:40 UTC, Nightlngale requested changes

2022-09-11 13:40 UTC, Nightlngale commented on packages/frontend/components/profile/user-account/my-list/cards/utils.ts
> +  array[Math.floor(Math.random() * array.length)];
I think it's fine to keep only 1 image

2022-09-11 19:49 UTC, Nightlngale approved these changes

2022-09-11 20:51 UTC, DmytroKolisnyk2 approved these changes

2022-09-11 20:56 UTC, merged

2022-09-11 21:41 UTC, dannleed commented on packages/backend/src/repositories/my-list.ts
> +      select: {
i've added an order entity that is needed for payment service, so i think we need added it here, when check is the product was already purchased

2022-09-11 21:41 UTC, dannleed commented on packages/backend/src/repositories/my-list.ts
> +        status: ProductStatus.FINISHED,
also that i write above is actual for this method

2022-09-11 21:41 UTC, dannleed commented on packages/frontend/components/profile/user-account/my-list/component.tsx
> +  // const myList = useTypedSelector((state: RootState) => state.myList.itemsList);
why this commented code here?