vse-bude-task#10: added email service
BinaryStudioAcademy/bsa-2022-vse-bude pull request #39
Opened 2022-08-10 12:12 UTC by vladyslav-soltanovskyi

I made an email service and added the **sendGreetingTo** method for an example of sending messages to the mailI made an email service and added the sendGreetingTo method for an example of sending messages to the mail

2022-08-10 12:48 UTC, Vitalii4as requested changes

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/.env.example
> -DATABASE_URL="postgresql://postgres:postgres@localhost:5432/vsebude_db?schema=public"
Why you deleted .env.example? 
It should exist. Also add here envs you used

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/repositories/mailer.ts
> +export class MailerRepository {
Create interface `IEmailProvider`
Create file `src/providers/email/SendInBlueEmailProvider.ts` and move all this to that file. implement IEmailProvider.

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/repositories/index.ts
> +  mailerRepository: new MailerRepository(),
Remove It

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/services/index.ts
> +  mailerService: new MailerService(repositories.mailerRepository),
just emailService

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/services/mailer.ts
> +export class MailerService {
Just EmailService

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/services/mailer.ts
> +    constructor(mailerRepository: MailerRepository) {
Recieve IEmailProvider

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/services/mailer.ts
> +    public async sendGreetingTo(email: string) {
Just `send` method with email and body (or content) parameters

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/services/index.ts
>  export const initServices = (repositories: Repositories) => ({
Create provider instance here and pass it to the EmailService

2022-08-10 12:48 UTC, Vitalii4as commented on packages/backend/src/repositories/mailer.ts
> +export class MailerRepository {
We need interface to easily change provider (for example from SendInBlue to SendGrid or any other)

2022-08-10 13:13 UTC, Nightlngale requested changes

2022-08-10 13:13 UTC, Nightlngale commented on packages/backend/src/services/index.ts
> +  mailerService: new MailerService(repositories.mailerRepository),
emailSenderService

2022-08-15 10:25 UTC, Vitalii4as requested changes

2022-08-15 10:25 UTC, Vitalii4as commented on packages/backend/.env.example
> +EMAIL_SERVICE_ADDRESS=
Why you added `EMAIL_SERVICE_ADDRESS`? You don't use it. Is it required for SDK?

2022-08-15 10:25 UTC, Vitalii4as commented on packages/backend/src/common/types/providers/IEmailProvider.ts
> +export interface IEmailProvider {
Please use for interface custom classes. It needed to easily change the provider. Return just Promise<boolean> - either sent successfully or not. As arguments it should require only email of a user and actual message

2022-08-15 14:57 UTC, Vitalii4as commented on packages/backend/src/providers/email/SendInBlueEmailProvider.ts
> +    return await this._apiInstance.sendTransacEmail({
return `Promise<boolean>` - either sent successfully or not.

2022-08-16 07:19 UTC, Vitalii4as approved these changes

2022-08-16 07:19 UTC, merged