VB-324: fix date localization at post form; change datePicker validating
BinaryStudioAcademy/bsa-2022-vse-bude pull request #393
Opened 2022-09-13 11:00 UTC by voonya

2022-09-13 11:23 UTC, Nightlngale requested changes

2022-09-13 11:23 UTC, Nightlngale commented on packages/frontend/components/primitives/input/date-input.tsx
> +          minDate={Date.now() + 86400000}
move to constant

2022-09-13 11:23 UTC, Nightlngale commented on packages/frontend/validation-schemas/post/create-auction.ts
> +      .min(Date.now() + 1000 * 60 * 60 * 24)
same here

2022-09-14 10:55 UTC, YevheniiBieliaiev approved these changes

2022-09-15 09:36 UTC, Nightlngale approved these changes

2022-09-15 09:36 UTC, merged