Feature/search
BinaryStudioAcademy/bsa-2022-vse-bude pull request #396
Opened 2022-09-13 13:35 UTC by double-hope

2022-09-13 14:17 UTC, dannleed commented on packages/frontend/components/primitives/search/component.tsx
> +    await dispatch(actionSearch(target.value.toString()));
maybe we can add debounce or throttle function here to send a search request with some interval but not on every onChange action, for example every 100ms or other value that will fit

2022-09-13 14:17 UTC, dannleed commented on packages/frontend/components/primitives/search/component.tsx
> +    await dispatch(actionSearch(''));
if you need clear state i think sending empty request not the best idea
create clearSearch action or handle empty string in existing action

2022-09-13 14:17 UTC, dannleed commented on packages/mobile/src/screens/home/home.tsx
>              placeHolder={t('home.SEARCH_PLACEHOLDER')}
why you do this?))

2022-09-13 15:12 UTC, double-hope commented
![image](https://user-images.githubusercontent.com/78951348/189939150-d8987ef4-a1ef-447c-9acc-361e2efac757.png)
![image](https://user-images.githubusercontent.com/78951348/189939154-758efff5-86df-4c28-a0d3-ecf15241cc4e.png)

2022-09-13 15:12 UTC, double-hope commented
![image](https://user-images.githubusercontent.com/78951348/189939234-e4cae67f-e6ea-490d-b367-c5127e2eb790.png)

2022-09-13 16:01 UTC, double-hope commented
![image](https://user-images.githubusercontent.com/78951348/189950533-35313e5f-21ca-4fa8-8b02-da660fca391e.png)
![image](https://user-images.githubusercontent.com/78951348/189950536-4c13f3ac-5952-4f18-b4c1-9de20ec916a6.png)
screen with search button

2022-09-13 20:19 UTC, dannleed approved these changes

2022-09-14 07:02 UTC, voonya approved these changes

2022-09-14 15:07 UTC, Nightlngale requested changes

2022-09-14 15:07 UTC, Nightlngale commented on packages/frontend/components/header/component.tsx
> +
Use it outside of the component. Add input/icon as a suspense

2022-09-15 07:12 UTC, Nightlngale approved these changes

2022-09-15 07:19 UTC, merged