Feature/notifications fe
BinaryStudioAcademy/bsa-2022-vse-bude pull request #439
Opened 2022-09-16 10:15 UTC by DmytroKolisnyk2

2022-09-16 10:45 UTC, voonya approved these changes

2022-09-16 10:49 UTC, dannleed approved these changes

2022-09-16 13:04 UTC, Nightlngale requested changes

2022-09-16 13:04 UTC, Nightlngale commented on packages/frontend/components/header/profile-info/notifications-wrapper/component.tsx
> +      ) : (
lets have:
```
if (loading) {
  return <Loader />
}

return <></>
```

2022-09-16 13:04 UTC, Nightlngale commented on packages/frontend/store/profile/actions.ts
> +  async (filter: NotificationQuery, { rejectWithValue }) =>
you can omit async

2022-09-17 17:07 UTC, YevheniiBieliaiev approved these changes

2022-09-19 12:52 UTC, DmytroKolisnyk2 commented
![Screenshot from 2022-09-19 15-51-50](https://user-images.githubusercontent.com/69747115/191021527-02bbaef7-0c6d-4a96-bb56-018ede00d8bd.png)
![Screenshot from 2022-09-19 15-51-25](https://user-images.githubusercontent.com/69747115/191021533-cc60e28e-f734-4116-9576-660e7362b455.png)

2022-09-19 16:27 UTC, Nightlngale approved these changes

2022-09-19 16:27 UTC, Nightlngale commented on packages/backend/src/repositories/notification.ts
> +    console.log(viewed);
log

2022-09-19 17:10 UTC, merged