VBM-194: add seller last name
BinaryStudioAcademy/bsa-2022-vse-bude pull request #455
Opened 2022-09-19 11:09 UTC by natata7

![Знімок екрана 2022-09-19 о 14 08 38](https://user-images.githubusercontent.com/10462332/191004518-b5b6bcd5-5a96-4d49-9e4b-e36b5d1dd0f3.png)

2022-09-19 11:15 UTC, VladimirBludov approved these changes

2022-09-19 11:35 UTC, VladimirBludov requested changes

2022-09-19 11:35 UTC, VladimirBludov commented on packages/mobile/src/screens/product-info/components/seller-info/seller-info.tsx
>              </Text>
may be better use `{'${firstName} ${lastName}'}`  that we will have one component, not three?

2022-09-19 12:31 UTC, VladimirBludov approved these changes

2022-09-20 10:33 UTC, Val-M9 approved these changes

2022-09-21 06:37 UTC, AleksandrTermenzhy approved these changes

2022-09-21 06:37 UTC, merged