VB-57: Feature/create header
BinaryStudioAcademy/bsa-2022-vse-bude pull request #63
Opened 2022-08-12 18:45 UTC by mishabenq

Just for review, what else needs to be done

2022-08-12 20:04 UTC, Nightlngale requested changes

2022-08-12 20:04 UTC, Nightlngale commented on packages/frontend/components/header/component.tsx
> +          <InternalLink href={Routes.DEFAULT} label="About us" />
Please use localised values. Update namespace common.

header: {
  nav: {
    ...
}
}

2022-08-12 20:04 UTC, Nightlngale commented on packages/frontend/components/header/component.tsx
> +            gap: '1em',
lets use css

2022-08-12 20:04 UTC, Nightlngale commented on packages/frontend/components/header/component.tsx
> +          maxWidth: '60%',
not sure about flexGrow: 2 and maxWidth 60%

2022-08-12 20:04 UTC, Nightlngale commented on packages/frontend/components/primitives/logo/component.tsx
> +export const Logo = () => <span css={styles.logo}></span>;
Let's use next/image

2022-08-16 13:22 UTC, Nightlngale requested changes

2022-08-16 13:22 UTC, Nightlngale commented on packages/frontend/components/header/component.tsx
> +export const HeaderLoggedOut = () => {
Use 1 header

2022-08-16 13:22 UTC, Nightlngale commented on packages/frontend/components/header/styles.ts
> +export const button_create_account_text = (theme: Theme) => css`
use camelCase

2022-08-16 17:29 UTC, mishabenq commented
![image](https://user-images.githubusercontent.com/92884408/184941798-20eed6f5-54eb-4687-8398-f1905cc094f9.png)
![image](https://user-images.githubusercontent.com/92884408/184941864-820e4603-b196-44e6-b90f-87e28137183e.png)
![image](https://user-images.githubusercontent.com/92884408/184941896-f750d268-76ac-4b16-9a04-09b05656d539.png)

2022-08-16 17:47 UTC, Nightlngale approved these changes

2022-08-16 18:14 UTC, merged