Feature/account page
BinaryStudioAcademy/bsa-2022-vse-bude pull request #70
Opened 2022-08-15 07:13 UTC by YevheniiBieliaiev

2022-08-15 14:44 UTC, YevheniiBieliaiev commented
![image](https://user-images.githubusercontent.com/84641178/184657239-ae3c8a4c-7d1e-4cab-aa22-3b73aae0c769.png)

2022-08-15 15:17 UTC, YevheniiBieliaiev commented
![image](https://user-images.githubusercontent.com/84641178/184663347-d6e2dd15-ee3d-451f-97ca-51e4acfe293c.png)

2022-08-16 07:58 UTC, Vitalii4as requested changes

2022-08-16 07:58 UTC, Vitalii4as commented on packages/frontend/pages/user-account/index.tsx
> +    console.log(store);
remove

2022-08-16 09:08 UTC, YevheniiBieliaiev commented on packages/frontend/pages/user-account/index.tsx
> +    console.log(store);
done

2022-08-16 11:52 UTC, Vitalii4as approved these changes

2022-08-16 11:52 UTC, merged