Feature/home page
BinaryStudioAcademy/bsa-2022-vse-bude pull request #98
Opened 2022-08-18 20:08 UTC by mozzie2004

2022-08-19 06:00 UTC, Nightlngale requested changes

2022-08-19 07:23 UTC, mozzie2004 commented on packages/frontend/components/home/category-section/component.tsx
> +  }));
it is needed only for the demo, because there are bad pictures in the database

2022-08-19 07:26 UTC, mozzie2004 commented on packages/frontend/components/home/component.tsx
> +  );
in filter page we will work with allProducts

2022-08-19 08:26 UTC, mozzie2004 commented on packages/frontend/components/home/category-section/component.tsx
> +              data-is-right={!((i + 1) % 4)}
I thought that more cards would be uploaded. Now made easier
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/70477606/185575083-9f812c07-f7e6-4793-8916-ac56808d59bb.png">

2022-08-19 10:26 UTC, Nightlngale commented on packages/frontend/components/home/category-section/component.tsx
> +              [lightTheme.breakpoints.xl]: {
`import { useTheme } from @emotion/react`

for now, you can add type: const theme: Theme = useTheme();

2022-08-19 10:28 UTC, Nightlngale commented on packages/frontend/components/home/category-section/component.tsx
> +              data-is-right={!((i + 1) % 4)}
please also add priority property to these images

2022-08-19 10:52 UTC, Nightlngale commented on packages/frontend/components/home/component.tsx
> +  );
yes, what if whatever reason we decided to have "almost" same auctionProducts and sellingProducts for one more page?

2022-08-23 07:48 UTC, Nightlngale approved these changes

2022-08-23 07:48 UTC, merged